import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

// Run manually with an unmodified PR8 checkout and an output directory.
// Regression tests load the committed SQL; they never run current code to
// manufacture a supposedly old schema or rely on a sibling checkout.
const PR8 = "6e7aa2ba4c27f6c4c375d5bc4bd4124decc20647";
const checkout = resolve(process.argv[2]!);
const output = resolve(process.argv[3]!);
if (execFileSync("git", ["rev-parse", "HEAD"], { cwd: checkout, encoding: "utf8" }).trim() !== PR8
  || execFileSync("git", ["status", "--porcelain", "--", "src"], { cwd: checkout, encoding: "utf8" }).trim()) {
  throw new Error("Fixture generation requires unmodified PR8 source at the recorded commit");
}
const { SqliteConversationStore } = await import(pathToFileURL(join(checkout, "src/conversations/sqlite-conversation-store.ts")).href) as typeof import("../../../../src/conversations/sqlite-conversation-store");
const { createSqlDriver } = await import(pathToFileURL(join(checkout, "src/conversations/sql-driver.ts")).href) as typeof import("../../../../src/conversations/sql-driver");
const path = join(mkdtempSync(join(tmpdir(), "xacpx-pr8-fixture-")), "conversations.sqlite");
const NOW = "2026-10-05T00:00:00.000Z";
const store = await SqliteConversationStore.open(path, { ids: {
  runId: () => "run_pr8_explicit", messageId: () => "cmsg_pr8_request",
  memberTurnId: () => "mturn_pr8_explicit", dispatchId: () => "pdsp_pr8_explicit",
} });
const accepted = store.acceptRequest({ conversationId: "conversation_pr8_explicit", topicId: "topic_pr8_explicit",
  requestId: "pr8-human-request", botId: "bot_a", content: "PR8 HUMAN REQUEST", now: NOW,
  authorityEpoch: "pr8-epoch", humanIngress: { chatKey: "relay:test", senderId: "human", chatType: "direct" },
  primaryMember: { effect: "unknown" },
  profileSnapshot: { revision: 1, capturedAt: NOW, presentation: { name: "A" }, behavior: {},
    execution: { agent: "codex", workspace: "backend" } },
});
if (accepted.run.maxMemberTurns !== 1) throw new Error("Expected the real PR8 single-member budget");
const db = await createSqlDriver(path);
if (db.all<{ name: string }>("PRAGMA table_info(runs)").some((column) => column.name === "budget_exhausted")) {
  throw new Error("Fixture source unexpectedly has PR9 schema");
}
function dump(state: "queued" | "claimed"): void {
  const schema = db.all<{ type: string; name: string; sql: string }>(
    "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type DESC, name");
  const value = (field: unknown): string => field === null ? "NULL"
    : typeof field === "number" ? String(field) : `'${String(field).replaceAll("'", "''")}'`;
  const quote = (name: string): string => `"${name.replaceAll('"', '""')}"`;
  const tables = schema.filter((item) => item.type === "table");
  const lines = [`-- Generated by PR8 source ${PR8}; no PR9 columns removed.`,
    `-- One explicit Group member; max_member_turns = 1; ${state}, no execution-start evidence.`,
    ...tables.map((table) => `${table.sql};`)];
  for (const table of tables) {
    for (const row of db.all<Record<string, unknown>>(`SELECT * FROM ${quote(table.name)} ORDER BY rowid`)) {
      lines.push(`INSERT INTO ${quote(table.name)} (${Object.keys(row).map(quote).join(", ")}) VALUES (${Object.values(row).map(value).join(", ")});`);
    }
  }
  lines.push(...schema.filter((item) => item.type !== "table").map((item) => `${item.sql};`));
  writeFileSync(join(output, `pr8-explicit-${state}.sql`), `${lines.join("\n\n")}\n`);
}
try {
  dump("queued");
  const claim = store.claimNextDispatch({ owner: "pr8-dead-owner", authorityEpoch: "pr8-epoch", now: NOW,
    leaseExpiresAt: "2026-10-05T00:01:00.000Z" });
  if (!claim || claim.memberTurn.startedAt) throw new Error("Expected actual PR8 claim without execution start");
  dump("claimed");
} finally { db.close(); store.close(); }
