-- Generated by PR8 source 6e7aa2ba4c27f6c4c375d5bc4bd4124decc20647; no PR9 columns removed.

-- One explicit Group member; max_member_turns = 1; queued, no execution-start evidence.

CREATE TABLE conversation_lifecycle (
  conversation_id TEXT PRIMARY KEY,
  state TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE member_turns (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  conversation_id TEXT NOT NULL,
  topic_id TEXT NOT NULL,
  bot_id TEXT NOT NULL,
  session_alias TEXT,
  logical_session_id TEXT,
  source_turn_id TEXT,
  queue_item_id TEXT,
  batch INTEGER NOT NULL DEFAULT 1,
  member_index INTEGER NOT NULL DEFAULT 0,
  attempt INTEGER NOT NULL DEFAULT 1,
  origin TEXT NOT NULL,
  state TEXT NOT NULL,
  trigger_message_ids_json TEXT NOT NULL,
  profile_snapshot_json TEXT,
  created_at TEXT NOT NULL,
  started_at TEXT,
  finished_at TEXT,
  failure_reason TEXT,
  assignment_id TEXT,
  task TEXT,
  expected_output TEXT,
  depends_on_json TEXT NOT NULL DEFAULT '[]'
, effect TEXT NOT NULL DEFAULT 'unknown', effect_provenance TEXT, blocked_reason TEXT);

CREATE TABLE messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  topic_id TEXT NOT NULL,
  seq INTEGER NOT NULL,
  role TEXT NOT NULL,
  sender_bot_id TEXT,
  content TEXT NOT NULL,
  run_id TEXT,
  source_turn_json TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (topic_id, seq)
);

CREATE TABLE pending_dispatches (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  member_turn_id TEXT NOT NULL,
  generation INTEGER NOT NULL,
  state TEXT NOT NULL,
  owner TEXT,
  lease_expires_at TEXT,
  authority_epoch TEXT,
  human_ingress TEXT,
  created_at TEXT NOT NULL,
  claimed_at TEXT,
  completed_at TEXT,
  UNIQUE (run_id, member_turn_id)
);

CREATE TABLE routing_decisions (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        decision_type TEXT NOT NULL,
        mode TEXT,
        question TEXT,
        reason TEXT,
        assignment_ids_json TEXT NOT NULL DEFAULT '[]',
        created_at TEXT NOT NULL
      );

CREATE TABLE runs (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  topic_id TEXT NOT NULL,
  request_message_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  mode TEXT NOT NULL,
  state TEXT NOT NULL,
  completion_reason TEXT,
  generation INTEGER NOT NULL,
  active_batch INTEGER,
  max_member_turns INTEGER NOT NULL,
  consumed_member_turns INTEGER NOT NULL,
  failed_bot_ids_json TEXT NOT NULL DEFAULT '[]',
  unavailable_bot_ids_json TEXT NOT NULL DEFAULT '[]',
  profile_revision INTEGER NOT NULL,
  profile_snapshot_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  started_at TEXT,
  finished_at TEXT, routing_state TEXT, routing_generation INTEGER NOT NULL DEFAULT 0, waiting_question TEXT,
  UNIQUE (conversation_id, topic_id, request_id)
);

CREATE TABLE topic_lifecycle (
  topic_id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  state TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE topic_seq (
  topic_id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  next_seq INTEGER NOT NULL
);

INSERT INTO "member_turns" ("id", "run_id", "conversation_id", "topic_id", "bot_id", "session_alias", "logical_session_id", "source_turn_id", "queue_item_id", "batch", "member_index", "attempt", "origin", "state", "trigger_message_ids_json", "profile_snapshot_json", "created_at", "started_at", "finished_at", "failure_reason", "assignment_id", "task", "expected_output", "depends_on_json", "effect", "effect_provenance", "blocked_reason") VALUES ('mturn_pr8_explicit', 'run_pr8_explicit', 'conversation_pr8_explicit', 'topic_pr8_explicit', 'bot_a', NULL, NULL, NULL, NULL, 1, 0, 1, 'human-explicit', 'queued', '["cmsg_pr8_request"]', '{"revision":1,"capturedAt":"2026-10-05T00:00:00.000Z","presentation":{"name":"A"},"behavior":{},"execution":{"agent":"codex","workspace":"backend"}}', '2026-10-05T00:00:00.000Z', NULL, NULL, NULL, NULL, NULL, NULL, '[]', 'unknown', NULL, NULL);

INSERT INTO "messages" ("id", "conversation_id", "topic_id", "seq", "role", "sender_bot_id", "content", "run_id", "source_turn_json", "created_at") VALUES ('cmsg_pr8_request', 'conversation_pr8_explicit', 'topic_pr8_explicit', 1, 'human', NULL, 'PR8 HUMAN REQUEST', 'run_pr8_explicit', NULL, '2026-10-05T00:00:00.000Z');

INSERT INTO "pending_dispatches" ("id", "run_id", "member_turn_id", "generation", "state", "owner", "lease_expires_at", "authority_epoch", "human_ingress", "created_at", "claimed_at", "completed_at") VALUES ('pdsp_pr8_explicit', 'run_pr8_explicit', 'mturn_pr8_explicit', 1, 'pending', NULL, NULL, 'pr8-epoch', '{"chatKey":"relay:test","senderId":"human","chatType":"direct"}', '2026-10-05T00:00:00.000Z', NULL, NULL);

INSERT INTO "runs" ("id", "conversation_id", "topic_id", "request_message_id", "request_id", "mode", "state", "completion_reason", "generation", "active_batch", "max_member_turns", "consumed_member_turns", "failed_bot_ids_json", "unavailable_bot_ids_json", "profile_revision", "profile_snapshot_json", "created_at", "started_at", "finished_at", "routing_state", "routing_generation", "waiting_question") VALUES ('run_pr8_explicit', 'conversation_pr8_explicit', 'topic_pr8_explicit', 'cmsg_pr8_request', 'pr8-human-request', 'explicit', 'queued', NULL, 1, 1, 1, 0, '[]', '[]', 1, '{"revision":1,"capturedAt":"2026-10-05T00:00:00.000Z","presentation":{"name":"A"},"behavior":{},"execution":{"agent":"codex","workspace":"backend"}}', '2026-10-05T00:00:00.000Z', NULL, NULL, NULL, 0, NULL);

INSERT INTO "topic_seq" ("topic_id", "conversation_id", "next_seq") VALUES ('topic_pr8_explicit', 'conversation_pr8_explicit', 1);

CREATE INDEX idx_dispatches_run ON pending_dispatches (run_id, state);

CREATE INDEX idx_dispatches_state ON pending_dispatches (state, created_at);

CREATE UNIQUE INDEX idx_member_assignment_unique ON member_turns (run_id, assignment_id) WHERE assignment_id IS NOT NULL;

CREATE INDEX idx_member_turns_run ON member_turns (run_id);

CREATE INDEX idx_messages_topic_seq ON messages (topic_id, seq);

CREATE INDEX idx_routing_decisions_run ON routing_decisions (run_id, created_at);

CREATE INDEX idx_runs_topic_state ON runs (topic_id, state, created_at);
